// Local development configuration
// In production, env.js is generated by nginx-runtime at container startup
// This file is only used for local development

(function (window) {
  window.__env = window.__env || {};
  window.__env.debugMode = true;
  
  // Local development defaults
  window.__env.ENVIRONMENT = 'local';
  window.__env.BANNER_COLOUR = 'red';
  window.__env.API_PATH = 'https://eagle-dev.apps.silver.devops.gov.bc.ca/api/public';
  window.__env.ADMIN_PATH = 'http://localhost:4200/admin/';
  window.__env.ANALYTICS_API_URL = 'http://localhost:3000';
  window.__env.ANALYTICS_DEBUG = true;
  window.__env.SURVEY_URL = null;
  window.__env.SHOW_SURVEY_BANNER = false;
}(this));
